# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/ip/GAME_WIN/GAME_WIN.xci
# IP: The module: 'GAME_WIN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/ip/GAME_WIN/GAME_WIN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GAME_WIN'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/ip/GAME_WIN/GAME_WIN.xci
# IP: The module: 'GAME_WIN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/ip/GAME_WIN/GAME_WIN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GAME_WIN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
