# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Project 2/ece540s16_project2_release_r1_0/project2_release/facing_north.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Project 2/ece540s16_project2_release_r1_0/project2_release/facing_north_east.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Project 2/ece540s16_project2_release_r1_0/project2_release/car_icon/facing_north.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Project 2/ece540s16_project2_release_r1_0/project2_release/car_icon/facing_north_east.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Project 2/ece540s16_project2_release_r1_0/project2_release/car_icon/facing_north__east_1.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/map.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/All_icons_with_coe/All_icons_with_coe/player_standing.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/All_icons_with_coe/All_icons_with_coe/opponent_standing.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/All_icons_with_coe/All_icons_with_coe/final_project_world_map_1024x512.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/3232icon_coefiles/player_standing.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/3232icon_coefiles/opponent_standing.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/corrected_coefiles/player_standing.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/corrected_coefiles/opponent_standing.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/_coefiles/player_standing.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/_coefiles/opponent_standing.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/corrected_coefiles/final_project_world_map_1024x512_with_hole.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Final/Images/correctedimagesofplayerwith_coefiles/player_standing.coe}}
add_files E:/System_on_Chip/Projects/Final/Images/3232icon_coefiles/final_project_world_map_1024x512_with_hole.coe
add_files E:/System_on_Chip/Projects/Final/map.coe
add_files E:/System_on_Chip/Projects/Final/Images/correctedimagesofplayerwith_coefiles/player_standing.coe
add_files E:/System_on_Chip/Projects/Final/Images/_coefiles/opponent_standing.coe
add_files E:/System_on_Chip/Projects/Final/Images/final_project_world_map_1024x512_with_hole_wo_sand_heaps.coe
add_files E:/System_on_Chip/Projects/Final/Images/3232icon_coefiles/player_running.coe
add_files E:/System_on_Chip/Projects/Final/Images/corrected_coefiles/opponent_climbing_up_down_left_foot_up.coe
add_files E:/System_on_Chip/Projects/Final/Images/_coefiles/player_running.coe
add_files E:/System_on_Chip/Projects/Final/Images/_coefiles/player_climbing_up_down_right_foot_up.coe
add_files E:/System_on_Chip/Projects/Final/Images/_coefiles/final_project_world_map_1024x512_with_hole_wo_sand_heaps.coe
add_files E:/System_on_Chip/Projects/Final/Images/_coefiles/player_standing.coe
add_files {{E:/System_on_Chip/Projects/Final/Images/Final Images/all_coefiles/opponent_climbing_up_down_left_foot_up.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Images/Final Images/all_coefiles/opponent_running.coe}}
add_files {{E:/System_on_Chip/Projects/Final/Images/Final Images/all_coefiles/final_project_world_map_1024x512_with_hole_wo_sand_heaps.coe}}
add_files e:/System_on_Chip/Projects/Final/Images/All_icons_with_coe/All_icons_with_coe/final_project_world_map_1024x512.coe
add_files e:/System_on_Chip/Projects/Final/Images/_coefiles/sand_heap.coe
add_files e:/System_on_Chip/Projects/Final/Images/remaining_corfiles/sand_heap.coe
add_files e:/System_on_Chip/Projects/Final/Images/remaining_corfiles/screen_1_final.coe
add_files e:/System_on_Chip/Projects/Final/Images/remaining_corfiles/game_over.coe
add_files e:/System_on_Chip/Projects/Final/Images/remaining_corfiles/modifiedicons/player_standing.coe
add_files e:/System_on_Chip/Projects/Final/Images/remaining_corfiles/modifiedicons/player_running.coe
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/World_map_synth_1/World_map.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/World_map_synth_1/World_map.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/ICON_Plyr_synth_1/ICON_Plyr.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/ICON_Plyr_synth_1/ICON_Plyr.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/Opnt_Icon1_synth_1/Opnt_Icon1.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/Opnt_Icon1_synth_1/Opnt_Icon1.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/plyr_run_e_synth_1/plyr_run_e.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/plyr_run_e_synth_1/plyr_run_e.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/ICON_PLYR_U_synth_1/ICON_PLYR_U.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/ICON_PLYR_U_synth_1/ICON_PLYR_U.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/Opnt1_Icon_U_synth_1/Opnt1_Icon_U.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/Opnt1_Icon_U_synth_1/Opnt1_Icon_U.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/Opnt1_Icon_R_synth_1/Opnt1_Icon_R.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/Opnt1_Icon_R_synth_1/Opnt1_Icon_R.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/MAIN_SCRN_synth_1/MAIN_SCRN.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/MAIN_SCRN_synth_1/MAIN_SCRN.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/snd_hp_synth_1/snd_hp.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/snd_hp_synth_1/snd_hp.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/GAME_OVER_synth_1/GAME_OVER.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/GAME_OVER_synth_1/GAME_OVER.dcp}}]
add_files -quiet {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/GAME_WIN_synth_1/GAME_WIN.dcp}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.runs/GAME_WIN_synth_1/GAME_WIN.dcp}}]
read_verilog -library xil_defaultlib {
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/non_pico_keybrd/debouncer.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/non_pico_keybrd/kbrd.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/hdl_part1/world_if.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/hdl_part1/map.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/hdl_part1/kcpsm6.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Picoblaze Code for Provider/provider_mod.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Sand Heap/sand_heap_algo.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/hdl_part1/modified_colorizer.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/Opnt_algo_v/opnt_trl_chetan.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/hdl_part1/sevensegment.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/hdl_part1/modified_icon.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/non_pico_keybrd/kybrd_if.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/hdl_part2/dtg.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/hdl_part1/debounce.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/imports/hdl_part1/bot.v}
  {E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/sources_1/new/n4fpga.v}
}
read_xdc {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/constrs_1/imports/constraints/nexys4fpga_novideo.xdc}}
set_property used_in_implementation false [get_files {{E:/System_on_Chip/Projects/Final/Project 2/project_1/project_1.srcs/constrs_1/imports/constraints/nexys4fpga_novideo.xdc}}]

synth_design -top n4fpga -part xc7a100tcsg324-1
write_checkpoint -noxdef n4fpga.dcp
catch { report_utilization -file n4fpga_utilization_synth.rpt -pb n4fpga_utilization_synth.pb }
